Vagrant.configure("2") do |config|
  config.vm.define "sonarqube" do |sonar|
    sonar.vm.box = "centos/7"
    sonar.vbguest.auto_update = false
    sonar.vbguest.installer_options = { allow_kernel_upgrade: true }
    sonar.vm.network "forwarded_port", guest: 9000, host: 9000, hostip: "127.0.0.1"
    sonar.vm.network "private_network", ip: "192.168.1.6"
    sonar.vm.hostname = "sonarqube"
    sonar.vm.provision "shell", path: "provision.sh"
    sonar.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
      v.name = "sonarqube"
      v.customize ["modifyvm", :id, "--groups", "/lab-sonarqeube"]
    end
  end
end
