---
- name: Configurar servidor de banco de dados
  hosts: db01
  

  user: vagrant
  become: yes
  ##vars_files:
  #  - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"    

  roles:
    - role: configuracao-defaults-so
    - role: geerlingguy.mysql      
...
