Vagrant.configure("2") do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/7"
    docker.vbguest.auto_update = false
    docker.vbguest.installer_options = { allow_kernel_upgrade: true }
    docker.vm.provision "shell", path: "provision.sh"
    docker.vm.hostname = "docker"
    docker.vm.provider "virtualbox" do |v|
      v.cpus = 6
      v.memory = "4096"
      v.name = "docker"
      v.customize ["modifyvm", :id, "--groups", "/lab-docker"]
    end
  end
end
