$ansible=<<-EOF
    ansible-galaxy install geerlingguy.mysql
EOF

nodes = {
    "control-node" => {"memory" => "2048", "cpu" => "4", "ip" => "2", "name" => "control-node"},
    "app01" => {"memory" => "2048", "cpu" => "4", "ip" => "3", "name" => "app01"},
    "db01" => {"memory" => "2048", "cpu" => "4", "ip" => "4", "name" => "db01"}
}

Vagrant.configure("2") do |config|
    nodes.each do |name, conf|
        config.vm.define "#{name}" do |node|
            node.vm.box = "centos/7"
            node.vbguest.auto_update = false
            node.vbguest.installer_options = { allow_kernel_upgrade: true }
            node.vm.hostname = "#{name}"
            node.vm.network "private_network", ip: "192.168.1.#{conf["ip"]}"            
            node.vm.provider "virtualbox" do |v|
                v.cpus = conf["cpu"]
                v.memory = conf["memory"]
                v.name = "#{name}"
                v.customize ["modifyvm", :id, "--groups", "/lab-ansible"]
            end
            node.vm.provision "shell", inline: <<-SHELL
                sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
                systemctl restart sshd.service                
                SHELL
            if "#{conf["name"]}" == "control-node"
                node.vm.synced_folder ".", "/vagrant", type: "nfs"
                node.vm.provision "shell", path: "provision.sh"
                node.vm.provision "shell", path: "generate_ssh_key.sh", privileged: false
                node.vm.provision "shell", inline: $ansible, privileged: false            

            elsif "#{conf["name"]}" == "app01" 
                node.vm.network "forwarded_port", guest: "8080", host: "8080", host_ip: "127.0.01"  
                node.vm.provision "shell", path: "ssh_key.sh"              
            
            elsif "#{conf["name"]}" == "db01"
                node.vm.network "forwarded_port", guest: "3306", host: "3306", host_ip: "127.0.01" 
                node.vm.provision "shell", path: "ssh_key.sh"
            end
        end
    end
end