Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "centos/7"
    jenkins.vbguest.auto_update = false
    jenkins.vbguest.installer_options = { allow_kernel_upgrade: true }
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, hostip: '127.0.0.1'
    jenkins.vm.network "private_network", ip: "192.168.1.5"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provision "shell", path: "provision.sh"
    jenkins.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
      v.name = "jenkins"
      v.customize ["modifyvm", :id, "--groups", "/lab-jenkins"]
    end
  end
end
